runtime: nodejs18
service: talento
runtime_config:
  operating_system: "ubuntu22"
  runtime_version: 18
#env: flex
env_variables:
  NODE_ENV: production
instance_class: F2
automatic_scaling:
  max_instances: 10
  min_instances: 0
  target_cpu_utilization: 0.75
handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
